# Generates the package documentation via Documenter.jl,
# and deploys it to Github Pages, as per the hosting guide
# at https://documenter.juliadocs.org/stable/man/hosting/

name: Documentation


# Regenerate doc whenever the below main is updated, or
# the workflow is manually triggered from the Actions tab
on:
  push:
    branches:
      - main
  workflow_dispatch:


# prevent concurrent doc gen
concurrency:
    group: doc
    cancel-in-progress: false


# give both doc-gen and tidy jobs below necessary 
# access to read/write from the gh-pages branch
permissions:
    actions: write
    contents: write
    pull-requests: read
    statuses: write


jobs:

  # regenerate the doxygen using Documenter.jl
  # and re-deploy it to the gh-pages branch
  build-doc:
    name: Build and deploy documentation
    runs-on: ubuntu-latest

    steps:

      # generate doc using files from the triggering branch
      - name: Obtain PP
        uses: actions/checkout@v4
    
      - name: Setup Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1'

      # using cache speeds up workflow
      - name: Setup Julia cache
        uses: julia-actions/cache@v2

      - name: Install dependencies
        shell: julia --color=yes --project=docs {0}
        run: |
          using Pkg
          Pkg.develop(PackageSpec(path=pwd()))
          Pkg.instantiate()

      - name: Build and deploy
        run: julia --color=yes --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # delete superfluous files remaining on the 
  # gh-pages branch to speed up user cloning
  tidy-doc:
    name: Tidy documentation
    runs-on: ubuntu-latest

    # perform this after doc regen
    needs: build-doc

    steps:

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      # make a cleaning commit as "Documenter.jl" bot
      - name: Delete preview and history + push changes
        run: |
          if [ -d "${preview_dir}" ]; then
              git config user.name "Documenter.jl"
              git config user.email "documenter@juliadocs.github.io"
              git rm -rf "${preview_dir}"
              git commit -m "delete preview"
              git branch gh-pages-new "$(echo "delete history" | git commit-tree "HEAD^{tree}")"
              git push --force origin gh-pages-new:gh-pages
          fi
        env:
          preview_dir: previews/PR${{ github.event.number }}
